# docker-compose.yml
version: '3.8'
services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopassword # 确保与 MONGO_URI 匹配
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: